version: '2'
services:
  bootstrap:
    build: monitored-geth-client
    restart: on-failure
    container_name: bootstrap
    hostname: alexbootstrap
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --unlock "0xcd2051a37cdc02db5da21d61415de21af4058a5e" --password /root/files/password --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=5555 --rpc --rpcaddr="0.0.0.0"'
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/devchain/keystore:rw
      - ./files/static-nodes.json:/root/.ethereum/devchain/static-nodes.json
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  eth1:
    build: monitored-geth-client
    restart: on-failure
    hostname: alexminer1
    links:
      - bootstrap
    entrypoint: /root/start.sh
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/devchain/keystore:rw
      - ./files/static-nodes.json:/root/.ethereum/devchain/static-nodes.json
    command: '--datadir=~/.ethereum/devchain --unlock "0xcd2051a37cdc02db5da21d61415de21af4058a5e" --password /root/files/password --rpccorsdomain="*" --networkid=5555 --rpc --mine'
  eth2:
    build: monitored-geth-client
    restart: on-failure
    hostname: alexminer2
    links:
      - bootstrap
    entrypoint: /root/start.sh
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/devchain/keystore:rw
      - ./files/static-nodes.json:/root/.ethereum/devchain/static-nodes.json
    command: '--datadir=~/.ethereum/devchain --unlock "0xcd2051a37cdc02db5da21d61415de21af4058a5e" --password /root/files/password --rpccorsdomain="*" --networkid=5555 --rpc --mine'
