version: '2'
services:
  geth:
    image: ethereum/client-go
    command: --datadir=/root/.ethereum/devchain ---networkid=5555 --unlock "0xcd2051a37cdc02db5da21d61415de21af4058a5e" --rpc --rpccorsdomain "*" init=/root/files/genesis.json --mine
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/devchain/keystore:rw
      - ./files/static-nodes.json:/root/.ethereum/devchain/static-nodes.json
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
