version: '2'
services:
  bootstrap:
    build: monitored-geth-client
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    links:
      - netstats
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --unlock "0xcd2051a37cdc02db5da21d61415de21af4058a5e" --password /root/files/password/password --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=5555 --rpc --rpcaddr="0.0.0.0"'
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/devchain/keystore:rw
      - ./files/static-nodes.json:/root/.ethereum/devchain/static-nodes.json
      - ~/etc/localtime:/etc/localtime:ro
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  eth:
    build: monitored-geth-client
    restart: on-failure
    links:
      - bootstrap
      - netstats
    entrypoint: /root/start.sh
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/devchain/keystore:rw
      - ./files/static-nodes.json:/root/.ethereum/devchain/static-nodes.json
      - ~/etc/localtime:/etc/localtime:ro
    command: '--datadir=~/.ethereum/devchain --unlock "0xcd2051a37cdc02db5da21d61415de21af4058a5e" --password /root/files/password/password --rpccorsdomain="*" --networkid=5555 --rpc'
  netstats:
    build: eth-netstats
    restart: on-failure
    container_name: netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    volumes:
      - ~/etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
